using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace PlanScoreCard.API.Models.ScoreCard
{
    public class StructureModel
    {

        public string StructureId { get; set; }
        public string StructureComment { get; set; }
        public string TemplateStructureId { get; set; }
        public string StructureCode { get; set; }
        public bool AutoGenerated { get; set; }
        public ObservableCollection<StructureModel> PlanStructureMatches { get; private set; }
        public StructureModel MatchedStructure { get; set; }
        public StructureModel()
        {
            PlanStructureMatches = new ObservableCollection<StructureModel>();
        }

    }
}
